### ISSUE TITLE
Different project titles in section 2.3 and 2.4 

### ISSUE THREAD

**Issue by eugenividal** [ITSLeeds/QGIS-intro#20]
One more comment on the material - I found confusing that the title of the project is different in section 2.3 (learning-qgis) and 2.4 (QGIS_Intro). In addition, I think some information referring to the QGIS Projects (section 2.3) is in Setting a coordinate reference system (CRS) (section 2.4.). I mean, I would locate the last paragraphs of 2.4 (From "You can create...") in section 2.3.

**Comment by DrIanPhilips** [comment]
Made edits as a pull request for @Robinlovelace

**Comment by Robinlovelace** [comment]
Heads-up @eugenividal the updated sections can be found here: https://itsleeds.github.io/QGIS-intro/working-with-qgis.html#qgis-projects

Does that fix the issue for you?

Cc @DrIanPhilips

**Comment by eugenividal** [comment]
It does ;-). Perfect!

**Comment by Robinlovelace** [comment]
Please mark the issue as closed then @eugenividal.

Many thanks for input :+1:

**Comment by eugenividal** [comment]
Done!
