### ISSUE TITLE
Comments on the SSPA module's material

### ISSUE THREAD

**Issue by eugenividal** [ITSLeeds/QGIS-intro#8]
Here some comments on the material for the module SSPA I thought could be useful to improve students’ understanding. 

- [x] In section 6.0.1, bullets points do not start in different paragraphs

- [x] In  section 7.1, the task explanation is not finished

- [x] In section 7.2, it is not clear how to get the LSOA boundaries – I
would do a link to the chapter 3 releases section. 

- [x] In section 7.2.2, you repeat “In the Vector Menu, select Data
Management Tools, Select Attributes by location”. Moreover, the section
is uncompleted, it ends up saying “in the stas19 data now has the...”

- [ ] In section 7.3, I’ll mention that because the variable is continuous
a graduated map is needed.

- [ ] In section 9.1, I would add a link to the releases section in chapter 3.

- [ ] In section 9.2, I’ll explain how to save the result as a new layer.

- [ ] In section 9.5, there is a figure missing - [ ] Figure ??.

Hope it helps!

**Comment by Robinlovelace** [comment]
Many thanks @eugenividal for these comments, very useful. We will work through these. @mem48 and @DrIanPhilips are you up for having a look at these? Let me know if you're up for addressing any of the quick fixes. We should aim to get these fixed before teaching begins.
